language: python
dist: xenial
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run python -m pytest --cov
after_success:
  - pipenv run bash <(curl -s https://codecov.io/bash)
